-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 19:38:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdacessibilidade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdacessibilidade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdacessibilidade` DEFAULT CHARACTER SET utf8mb3 ;
USE `bdacessibilidade` ;

-- -----------------------------------------------------
-- Table `bdacessibilidade`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdacessibilidade`.`tb_usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `senha` VARCHAR(60) NULL DEFAULT NULL,
  `cpf` VARCHAR(13) NULL DEFAULT NULL,
  `data_cadastro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdacessibilidade`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdacessibilidade`.`tb_produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome_anunciante` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `produto` VARCHAR(60) NOT NULL,
  `categoria` ENUM('Cadeiras', 'Andadores', 'Muletas', 'Outros') NOT NULL,
  `oferta` ENUM('Pago', 'Gratuito', 'Doação') NOT NULL,
  `valor` VARCHAR(15) NOT NULL,
  `descricao` VARCHAR(120) NOT NULL,
  `nome_arquivo` VARCHAR(120) NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `data_upload` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tb_usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_produtos`),
  INDEX `fk_tb_produtos_tb_usuarios_idx` (`tb_usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_usuarios`
    FOREIGN KEY (`tb_usuarios_id_usuarios`)
    REFERENCES `bdacessibilidade`.`tb_usuarios` (`id_usuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdacessibilidade`.`tb_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdacessibilidade`.`tb_enderecos` (
  `id_enderecos` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `localidade` VARCHAR(60) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `tb_produtos_id_produtos` INT NOT NULL,
  `id_usuario` VARCHAR(10) NOT NULL,
  `data_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_enderecos`),
  INDEX `fk_tb_enderecos_tb_produtos1_idx` (`tb_produtos_id_produtos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_enderecos_tb_produtos1`
    FOREIGN KEY (`tb_produtos_id_produtos`)
    REFERENCES `bdacessibilidade`.`tb_produtos` (`id_produtos`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdacessibilidade`.`tb_area_interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdacessibilidade`.`tb_area_interesse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_usuarios_id_usuarios` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `categoria_interesse` ENUM('Cadeiras', 'Andadores', 'Muletas', 'Outros') NOT NULL,
  `data_interesse` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_area_interesse_tb_usuarios1_idx` (`tb_usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_area_interesse_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id_usuarios`)
    REFERENCES `bdacessibilidade`.`tb_usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
